### ISSUE TITLE
[BUG] Search instance type doesn't seem to work

### ISSUE THREAD

**Issue by Puneeth-n** [Oisins/ubuntu_ami_query#2]
When i want to search for the latest AMI with instance type hvm:ebs `./ubuntu_ami_query.py -i hvm:ebs` The code returns the AMI ID `ami-7c4b0a0b` which is `ebs` and not `hvm:ebs`

http://cloud-images.ubuntu.com/locator/ec2/

**Comment by Oisins** [comment]
Fixed! Must use `^hvm:ebs`
