### ISSUE TITLE
[Suggestion] argparse Version

### ISSUE THREAD

**Issue by Puneeth-n** [Oisins/ubuntu_ami_query#3]
w.r.t: https://github.com/Oisins/ubuntu_ami_query/blob/master/ubuntu_ami_query.py#L20

Instead of the version, It is nice to have a switch to search for LTS and non LTS AMIs may be search for the existence of `(lts, LTS)` in version?

This would also change the argparse behavior to something like `parser.add_argument("--non_lts", action="store_true", help="default behavious fetches only LTS")
`

**Comment by Oisins** [comment]
Alex said we don't need this.
