### ISSUE TITLE
[Suggestion] argparse options

### ISSUE THREAD

**Issue by Puneeth-n** [Oisins/ubuntu_ami_query#5]
`parser.add_argument("-re", dest="searchRelease", type=str, help="Search Release")
parser.add_argument("-amk", dest="searchAMI_ID", type=str, help="Search AMI_ID")
parser.add_argument("-aki", dest="searchAKI_ID", type=str, help="Search AKI_ID")`

I can't think of a reason for having these options as these are the parameters this program is supposed to fetch especially the `AMI_ID`

**Comment by Oisins** [comment]
Done!
