### ISSUE TITLE
[Feature Request] Create/Update properties file

### ISSUE THREAD

**Issue by Puneeth-n** [Oisins/ubuntu_ami_query#6]
It would be nice to have in this code the functionality to read and update the properties file when needed.

**Behaviour:**
- Create a new properties file if it doesn't exist
- Check the AMI_ID in the properties file and update the file if the AMI_ID is not the same

**Name of the file:** `ami_id.properties`
*\* Layout of a sample properties file **
`## This is a properties file with the latest ubuntu ami id available at ubuntu cloud images`
`AMI_ID = ami-123456`

**Comment by Oisins** [comment]
Feature Removed. Using Print instead
